server:
  port: 8088
  address: localhost

spring:
  application:
    name: databridge
#  profiles:
#    active:
#      - '@profile.active@'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.64.8/databridge?characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: Qwer1234
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: false

  aop:
    proxy-target-class: true

xxl-job:
  url: http://localhost:8080
  username: admin
  password: 123456

