server:
  port: 8081

xxl:
  job:
    accessToken:
    admin:
      addresses: http://123.126.105.108:8099/xxl-job-admin
    executor:
      address: ''
      appname: dataTransJobHandler
      ip: ''
      logpath: log/jobhandler
      logretentiondays: 30
      port: 9999

logging:
  config: classpath:logback.xml

databridge:
  url: http://127.0.0.1:8088

flinkx:
#  url: http://192.168.64.1:30080/
  url: http://123.126.105.37:9527/


logging:
  pattern:
    console: ${CONSOLE_LOG_PATTERN:%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} [${spring.application.name}] %clr([%10.10t]){faint}[%36.36X{trace_id}] %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}
    file: '${FILE_LOG_PATTERN:%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:%5p} ${PID:- } [${spring.application.name}] [%10.10t][%36.36X{trace_id}] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}'
  file:
    name: logs/${spring.application.name}.log
  level:
    com.haizhi: INFO
    com.haizhi.common.jdbc.repository.mapping.EntityTypeContext: INFO
    org.springframework.web: ERROR
    org.springframework.orm: ERROR
    org.springframework.scheduling: ERROR
    org.springframework.data: DEBUG
    org.springframework.data.repository.config.RepositoryConfigurationExtensionSupport: ERROR
    org.springframework.context: ERROR
    org.hibernate: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: INFO
    org.hibernate.SQL: INFO
    org.hibernate.engine.QueryParameters: INFO
    org.hibernate.engine.query.HQLQueryPlan: INFO
    org.apache.catalina: ERROR
    com.zaxxer.hikari: ERROR
