server:
  port: 8081

xxl:
  job:
    accessToken:
    admin:
      addresses: http://123.126.105.108:8099/xxl-job-admin
    executor:
      address: ''
      appname: dataTransJobHandler
      ip: ''
      logpath: log/jobhandler
      logretentiondays: 30
      port: 9999

logging:
  config: classpath:logback.xml

databridge:
  url: http://127.0.0.1:8088

flinkx:
#  url: http://192.168.64.1:30080/
  url: http://123.126.105.37:9527/

